FROM tensorflow/tensorflow:latest
EXPOSE 5000

# Create a working directory
RUN mkdir /app
WORKDIR /app

RUN pip3 install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
RUN pip3 install segmentation-models-pytorch pyradiomics scikit-image scikit-learn Flask scipy Pillow

COPY ./ /app
RUN chmod +x start_flask_dev.sh
ENTRYPOINT ["/bin/bash", "-c", "./start_flask_dev.sh"]
