FROM tensorflow/tensorflow:latest-gpu
EXPOSE 5000

RUN pip3 install torch==1.5.0+cu101 torchvision==0.6.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html
RUN pip3 install segmentation-models-pytorch pyradiomics scikit-image scikit-learn Flask scipy Pillow

WORKDIR /
COPY ./ /
RUN chmod +x start_flask_dev.sh

ENTRYPOINT ["/bin/bash", "-c", "./start_flask_dev.sh"]
